# Site settings
title: "/dev/log"
name:  "/dev/log"
email: thewisenerd@protonmail.com
description: "work blog of thewisenerd"
baseurl: ""
url: "http://thewisenerd.github.com"
title_description: "a work log written consisting largely of random articles and rants and otherwise articles seemingly picked from /dev/random or attempts at documenting projects by the author."
title_image: "/assets/fa-terminal_512_100_c0bebf_000000.png"
author:
  name:  "thewisenerd"
  email: "thewisenerd@protonmail.com"
  uri:   "http://thewisenerd.github.com/"
  image: "https://github.com/thewisenerd.png"
#google_analytics:
disqus_account: slashdevlog
github_repository: https://github.com/thewisenerd/thewisenerd.github.com
#addthis_id:
post_limit: 5

# Social usernames/URLs
#twitter_username:
github_username: thewisenerd
#linkedin_link:
#google_plus_link:
#stackoverflow_link:

# Footer
footer_left: "Made with <i class=\"fa fa-heart\"></i> by <a href=\"https://twitter.com/_JacobTomlinson\">Jacob Tomlinson</a>"
footer_right: "&lt;/&gt; on <a href=\"https://github.com/thewisenerd/thewisenerd.github.com\">Github</a> &nbsp;<i class=\"fa fa-github-alt\"></i>"

# Build settings
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript"]
permalink: pretty
exclude: [vendor]

gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-feed
